import React from 'react';
import { getProviders, signIn } from 'next-auth/react';
import Image from 'next/image';
import Head from 'next/head';
import img from '/public/home.png';

function Login({ providers }) {
  var myDate = new Date();
  var hrs = myDate.getHours();
  var message='';
  if(hrs<12){message = 'Good Morning'}
  else if(hrs>=12 && hrs<=17){message = 'Good Afternoon'}
  else if(hrs>=17 && hrs<=24){message = 'Good Evening'}
  return (
    <div className='flex flex-col items-center bg-black min-h-screen w-full justify-center'>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Image className='mb-3 object-contain' width={600} height={500} src={img} alt='' />
      <h1 className='text-gray-300 text-2xl italic font-light tracking-[5px]'>{message}</h1>
      <h2 className='text-gray-300 text-2xl italic font-light tracking-[5px] mb-12'>Welcome to Spotify 2.0</h2>
      {Object.values(providers).map((provider) => (
        <div key={provider.name}>
          <button 
          className='bg-[#18d860] text-white/90 text-lg p-4 rounded-full 
          font-semibold hover:shadow-md hover:shadow-[#18d860]/40' 
          onClick={() => signIn(provider.id, {callbackUrl:"/"})}>Login with {provider.name}</button>
        </div>
      ))}
    </div>
  )
}

export default Login;

export async function getServerSideProps() {
  const providers = await getProviders();
  return {
    props: {
      providers,
    },
  };
}